apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextself-prod
  labels:
    app: nextself
    type: frontend
    version: 1.0.0
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nextself
      type: frontend
      version: 1.0.0
  template:
    metadata: 
      labels:
        app: nextself
        type: frontend
        version: 1.0.0
    spec:
      containers:
        - name: nextself
          imagePullPolicy: Always
          image: wglint/nextself
          ports:
            - containerPort: 3000